version: '3'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: Web/Dockerfile
  web2:
    image: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
#    build:
#      context: .
#      dockerfile: Web/Dockerfile
  web3:
    image: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
#    build:
#      context: .
#      dockerfile: Web/Dockerfile
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
#    hostname: redis
#    networks:
#      - redis-net
#    volumes:
#      - redis-data:/data